from __future__ import annotations

"""
Recipe knowledge base — hand-curated recipes with ingredient matching.
Each recipe defines:
  - required: ingredients that must be present
  - optional: nice-to-have ingredients
  - missing: things commonly needed that users might not have
No external API needed.
"""

from typing import Any, Dict, List

RECIPES: List[Dict[str, Any]] = [
    # ─── Egg-based ───────────────────────────────────────────────────────────
    {
        "name": "Classic Scrambled Eggs",
        "cuisine": "american",
        "difficulty": "easy",
        "time_minutes": 8,
        "calories_per_serving": 220,
        "required": ["egg", "eggs"],
        "optional": ["butter", "milk", "cheese", "salt", "pepper", "chive", "chives"],
        "always_missing": [],
        "steps": [
            {"step": 1, "instruction": "Crack eggs into a bowl, add a splash of milk and whisk well", "time_minutes": 2},
            {"step": 2, "instruction": "Heat butter in a non-stick pan over low-medium heat", "time_minutes": 1},
            {"step": 3, "instruction": "Pour in eggs. Stir gently and continuously until just set", "time_minutes": 3},
            {"step": 4, "instruction": "Remove from heat while still slightly runny — residual heat finishes them", "time_minutes": 1},
            {"step": 5, "instruction": "Season with salt and pepper, top with chives if available"},
        ],
        "tips": ["Low and slow is the secret — high heat makes eggs rubbery", "Pull off heat 30 seconds early"],
        "dietary_ok": ["vegetarian", "gluten-free"],
    },
    {
        "name": "Fried Rice",
        "cuisine": "chinese",
        "difficulty": "easy",
        "time_minutes": 15,
        "calories_per_serving": 380,
        "required": ["rice"],
        "optional": ["egg", "eggs", "soy sauce", "garlic", "onion", "carrot", "pea", "peas", "spring onion", "sesame oil"],
        "always_missing": ["soy sauce"],
        "steps": [
            {"step": 1, "instruction": "Use day-old cold rice — fresh rice is too wet", "time_minutes": 0},
            {"step": 2, "instruction": "Heat oil in wok/pan on high. Add garlic and onion, stir-fry 1 min", "time_minutes": 2},
            {"step": 3, "instruction": "Add vegetables, stir-fry 2 min", "time_minutes": 2},
            {"step": 4, "instruction": "Push to side, scramble eggs in the empty space", "time_minutes": 2},
            {"step": 5, "instruction": "Add rice, break up clumps, mix everything together", "time_minutes": 3},
            {"step": 6, "instruction": "Add soy sauce and sesame oil, toss and serve"},
        ],
        "tips": ["High heat is essential for wok hei flavour", "Don't stir too much — let it crisp up"],
        "dietary_ok": ["dairy-free"],
    },
    {
        "name": "Garlic Pasta",
        "cuisine": "italian",
        "difficulty": "easy",
        "time_minutes": 20,
        "calories_per_serving": 440,
        "required": ["pasta"],
        "optional": ["garlic", "olive oil", "parmesan", "chili", "chili flakes", "parsley", "lemon"],
        "always_missing": ["parmesan"],
        "steps": [
            {"step": 1, "instruction": "Boil pasta in well-salted water until al dente (2 min less than package)", "time_minutes": 10},
            {"step": 2, "instruction": "While pasta cooks, thinly slice garlic", "time_minutes": 2},
            {"step": 3, "instruction": "Heat olive oil over low heat, add garlic — cook until golden (not brown!)", "time_minutes": 4},
            {"step": 4, "instruction": "Add chili flakes if using. Reserve 1 cup pasta water before draining", "time_minutes": 1},
            {"step": 5, "instruction": "Toss drained pasta in garlic oil, add pasta water to emulsify", "time_minutes": 2},
            {"step": 6, "instruction": "Finish with parmesan and parsley"},
        ],
        "tips": ["Pasta water is liquid gold — it makes the sauce silky", "Garlic burns fast, stay at low heat"],
        "dietary_ok": ["vegetarian"],
    },
    {
        "name": "Tomato Omelette",
        "cuisine": "chinese",
        "difficulty": "easy",
        "time_minutes": 10,
        "calories_per_serving": 250,
        "required": ["egg", "tomato"],
        "optional": ["eggs", "salt", "sugar", "oil", "spring onion", "onion"],
        "always_missing": [],
        "steps": [
            {"step": 1, "instruction": "Beat 3 eggs with a pinch of salt. Dice tomatoes", "time_minutes": 2},
            {"step": 2, "instruction": "Scramble eggs in hot oil until just set, set aside", "time_minutes": 3},
            {"step": 3, "instruction": "Stir-fry tomatoes 2 min, add a pinch of sugar", "time_minutes": 2},
            {"step": 4, "instruction": "Return eggs, toss gently, season and serve"},
        ],
        "tips": ["A little sugar balances the tomato acidity — classic trick"],
        "dietary_ok": ["vegetarian", "gluten-free", "dairy-free"],
    },
    {
        "name": "Avocado Toast",
        "cuisine": "american",
        "difficulty": "easy",
        "time_minutes": 7,
        "calories_per_serving": 310,
        "required": ["avocado", "bread"],
        "optional": ["egg", "lemon", "salt", "pepper", "chili flakes", "everything bagel seasoning"],
        "always_missing": [],
        "steps": [
            {"step": 1, "instruction": "Toast bread until golden"},
            {"step": 2, "instruction": "Mash avocado with salt, pepper, and lemon juice"},
            {"step": 3, "instruction": "Spread on toast, top with optional fried/poached egg"},
            {"step": 4, "instruction": "Add chili flakes or seasoning to taste"},
        ],
        "tips": ["Lemon juice prevents browning and adds brightness"],
        "dietary_ok": ["vegetarian", "dairy-free"],
    },
    {
        "name": "Vegetable Stir-Fry",
        "cuisine": "chinese",
        "difficulty": "easy",
        "time_minutes": 15,
        "calories_per_serving": 180,
        "required": [],
        "optional": ["broccoli", "carrot", "bell pepper", "capsicum", "mushroom", "zucchini", "snap pea",
                     "garlic", "ginger", "soy sauce", "oyster sauce", "sesame oil"],
        "always_missing": ["oyster sauce"],
        "needs_any": ["broccoli", "carrot", "bell pepper", "mushroom", "zucchini"],
        "steps": [
            {"step": 1, "instruction": "Prep all vegetables — cut into similar-sized pieces for even cooking"},
            {"step": 2, "instruction": "Heat wok on high, add oil"},
            {"step": 3, "instruction": "Add garlic and ginger first, stir 30 sec", "time_minutes": 1},
            {"step": 4, "instruction": "Add harder vegetables first (carrot, broccoli), stir-fry 3 min", "time_minutes": 3},
            {"step": 5, "instruction": "Add softer vegetables (mushroom, capsicum), stir-fry 2 min", "time_minutes": 2},
            {"step": 6, "instruction": "Add sauces, toss to coat. Serve immediately"},
        ],
        "tips": ["High heat + fast motion = restaurant texture", "Don't crowd the pan — cook in batches if needed"],
        "dietary_ok": ["vegetarian", "vegan", "gluten-free", "dairy-free"],
    },
    {
        "name": "Banana Pancakes",
        "cuisine": "american",
        "difficulty": "easy",
        "time_minutes": 15,
        "calories_per_serving": 280,
        "required": ["banana", "egg"],
        "optional": ["flour", "milk", "vanilla", "cinnamon", "honey", "maple syrup", "butter"],
        "always_missing": [],
        "steps": [
            {"step": 1, "instruction": "Mash 1 ripe banana. Beat in 2 eggs (this is your batter!)"},
            {"step": 2, "instruction": "For fluffier pancakes: add 2 tbsp flour and splash of milk"},
            {"step": 3, "instruction": "Heat non-stick pan with a little butter on medium-low"},
            {"step": 4, "instruction": "Pour small circles. Cook 2 min until bubbles form, flip once", "time_minutes": 4},
            {"step": 5, "instruction": "Serve with honey or maple syrup"},
        ],
        "tips": ["Riper banana = sweeter, easier to mash", "Keep heat medium-low — banana burns fast"],
        "dietary_ok": ["vegetarian", "gluten-free"],
    },
    {
        "name": "Miso Soup",
        "cuisine": "japanese",
        "difficulty": "easy",
        "time_minutes": 10,
        "calories_per_serving": 80,
        "required": ["miso paste"],
        "optional": ["tofu", "seaweed", "spring onion", "mushroom", "egg"],
        "always_missing": ["miso paste", "dashi"],
        "steps": [
            {"step": 1, "instruction": "Bring 2 cups water to near-boil (don't boil miso — kills the probiotics)"},
            {"step": 2, "instruction": "Dissolve 1-2 tbsp miso paste in a little warm water first"},
            {"step": 3, "instruction": "Add tofu cubes and any vegetables, simmer 2 min"},
            {"step": 4, "instruction": "Stir in dissolved miso. Add spring onion. Serve immediately"},
        ],
        "tips": ["Never boil miso — add it off the heat", "White miso = milder, red miso = deeper flavour"],
        "dietary_ok": ["vegetarian", "vegan", "gluten-free", "dairy-free"],
    },
    {
        "name": "Quesadilla",
        "cuisine": "mexican",
        "difficulty": "easy",
        "time_minutes": 12,
        "calories_per_serving": 420,
        "required": ["tortilla", "cheese"],
        "optional": ["chicken", "bell pepper", "onion", "jalapeño", "sour cream", "salsa", "avocado", "black bean"],
        "always_missing": [],
        "steps": [
            {"step": 1, "instruction": "Heat dry pan over medium heat"},
            {"step": 2, "instruction": "Place tortilla in pan, spread cheese on half"},
            {"step": 3, "instruction": "Add any fillings (cooked chicken, sautéed peppers, beans)"},
            {"step": 4, "instruction": "Fold tortilla over. Cook 2 min until golden, flip carefully, cook 2 more min", "time_minutes": 4},
            {"step": 5, "instruction": "Slice into wedges. Serve with sour cream or salsa"},
        ],
        "tips": ["Low heat = crispy without burning", "Add fillings sparingly or it won't fold"],
        "dietary_ok": ["vegetarian"],
    },
    {
        "name": "Tuna Salad",
        "cuisine": "american",
        "difficulty": "easy",
        "time_minutes": 8,
        "calories_per_serving": 290,
        "required": ["tuna"],
        "optional": ["mayonnaise", "onion", "celery", "lemon", "lettuce", "bread", "cucumber", "capers"],
        "always_missing": [],
        "steps": [
            {"step": 1, "instruction": "Drain tuna can thoroughly. Flake into a bowl"},
            {"step": 2, "instruction": "Finely dice any vegetables (onion, celery, cucumber)"},
            {"step": 3, "instruction": "Mix with mayo, a squeeze of lemon, salt and pepper"},
            {"step": 4, "instruction": "Serve on bread, crackers, or lettuce cups"},
        ],
        "tips": ["Greek yogurt works as a lighter mayo sub", "Let it rest 5 min for flavours to develop"],
        "dietary_ok": ["gluten-free", "dairy-free"],
    },
    {
        "name": "Congee (Rice Porridge)",
        "cuisine": "chinese",
        "difficulty": "easy",
        "time_minutes": 40,
        "calories_per_serving": 220,
        "required": ["rice"],
        "optional": ["ginger", "spring onion", "soy sauce", "sesame oil", "egg", "chicken", "century egg"],
        "always_missing": [],
        "steps": [
            {"step": 1, "instruction": "Rinse 1/2 cup rice, add to pot with 4-5 cups water or broth"},
            {"step": 2, "instruction": "Add sliced ginger (2-3 pieces). Bring to boil", "time_minutes": 5},
            {"step": 3, "instruction": "Reduce to low simmer, cook 25-30 min stirring occasionally until thick", "time_minutes": 30},
            {"step": 4, "instruction": "Top with spring onion, drizzle soy sauce and sesame oil"},
        ],
        "tips": ["Leftover rice cooks in half the time", "Chicken stock instead of water = much richer flavour"],
        "dietary_ok": ["gluten-free", "dairy-free", "vegetarian"],
    },
    {
        "name": "Spanish Omelette (Tortilla)",
        "cuisine": "mediterranean",
        "difficulty": "medium",
        "time_minutes": 25,
        "calories_per_serving": 320,
        "required": ["egg", "potato"],
        "optional": ["eggs", "onion", "olive oil", "salt", "pepper"],
        "always_missing": [],
        "steps": [
            {"step": 1, "instruction": "Peel and thinly slice 2 potatoes and 1 onion"},
            {"step": 2, "instruction": "Fry gently in olive oil on low heat until soft (15 min)", "time_minutes": 15},
            {"step": 3, "instruction": "Drain, then mix with 4 beaten eggs, season well"},
            {"step": 4, "instruction": "Cook in the pan on medium-low, 5 min until edges set"},
            {"step": 5, "instruction": "Flip onto plate, slide back into pan, cook 3 more min", "time_minutes": 3},
        ],
        "tips": ["The flip is the hard part — confidence is key!", "Serve warm or at room temperature"],
        "dietary_ok": ["vegetarian", "gluten-free", "dairy-free"],
    },
]
